apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: test-monitoreo
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        server_name localhost;
        location /stub_status {
          stub_status on;
          allow 127.0.0.1;
        }
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-de-prueba
  namespace: test-monitoreo
  labels:
    app: app-de-prueba
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-de-prueba
  template:
    metadata:
      labels:
        app: app-de-prueba
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9113"
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.10.0
        args:
          - -nginx.scrape-uri=http://localhost:80/stub_status
        ports:
          - containerPort: 9113
            name: metrics
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
          requests:
            memory: 64Mi
            cpu: 50m
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: app-de-prueba-service
  namespace: test-monitoreo
  labels:
    app: app-de-prueba
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9113"
spec:
  selector:
    app: app-de-prueba
  ports:
  - port: 80
    targetPort: 80
    name: web
  - port: 9113
    targetPort: 9113
    name: metrics
  type: ClusterIP